// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestInputGenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTestInputGeneratorPackageString = "c7e2c7ab-10ee-44bf-9b94-5c049d265377";
        public static Guid guidTestInputGeneratorPackage = new Guid(guidTestInputGeneratorPackageString);

        public const string guidTestInputGeneratorPackageCmdSetString = "0a10936b-5fe7-4e69-ad31-570a8ad89ee7";
        public static Guid guidTestInputGeneratorPackageCmdSet = new Guid(guidTestInputGeneratorPackageCmdSetString);

        public const string guidImagesString = "7a4da646-b78d-4854-bbee-d699d2343e04";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GeneratorToolWindowCommandId = 0x0100;
        public const int GeneratorTWMenu = 0x0200;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}